image:
  file: .gitpod.Dockerfile

tasks:
  - name: taskman application
    command: projen dev
  - name: Redis
    command: docker run -p 6379:6379 -p 8001:8001 redis/redis-stack:latest

ports:
    - name: Backend
      port: 8000
      onOpen: open-browser
    
github:
    prebuilds:
        master: true
        pullRequests: false
        addComment: false